- name: install and start nginx
  hosts: web
  become: yes #equal to -b in adhoc commands become root access
  tasks
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

