- name: variables from file
  hosts: localhost
  tasks:
  - name: print imformation
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}}, from trainer {{Trainer}} duration is {{Duration}}"