- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: Please enter the number
    private: no
  tasks:
  - name: check number is less than 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is lesser than or not"
    when: number | int < 10

  tasks:
  - name: check number is greaterthan or equal to than 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is greater than or equal to"
    when: number | int > 10
