- name: default value
  hosts: localhost
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: "Hello {{Course | default ('Ansible')}}"


- name: convert to uppercase
  hosts: localhost
  vars:
    greeting: "Hello, Good morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: convert to lowercase
  hosts: localhost
  vars:
    greeting: "Hello, Good morning"
  tasks:
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    number: [1, 2, 1, 4, 2, 5, 6]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{number | unique}}"

- name: min and max
  hosts: localhost
  vars:
    number: [1, 2, 1, 4, 2, 5, 6]
  tasks:
  - name: print min amd amx
    ansible.builtin.debug:
      msg: "{{number | min }}, {{number | max }}"

- name: convert dict to items
  hosts: localhost
  vars:
    my_dict:
      Course: Ansible
      Trainer: Siva
      Duration: 120hr
  tasks:
  - name: Before convert
    ansible.builtin.debug:
      msg: "before conver {{my_dict}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert {{my_dict | dict2items }}"

- name: convert items to dict
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansible'}
    - {'key': 'Trainer', 'value': 'Siva'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: Before convert
    ansible.builtin.debug:
      msg: "before conver {{my_list}}"
  - name: after convert
    ansible.builtin.debug:
      msg: "after convert {{my_list | items2dict }}"