- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'present' }
    - { name: 'postfix', state: 'absent' }